### ISSUE TITLE
NullPointerException in GHPerson

### ISSUE THREAD

**Issue by kuc** [kohsuke/github-api#111]
I'm not sure if I should report this here or to https://github.com/janinko/ghprb, but exception is thrown in `at org.kohsuke.github.GHPerson.populate(GHPerson.java:42)`.

I use `GitHub API Plugin 1.55` and `GitHub Pull Request Builder 1.12`.

```
Jul 14, 2014 6:54:53 PM WARNING org.jenkinsci.plugins.ghprb.GhprbPullRequest obtainAuthorEmail
Couldn't obtain author email.
java.lang.NullPointerException
	at org.kohsuke.github.GHPerson.populate(GHPerson.java:42)
	at org.kohsuke.github.GHPerson.getEmail(GHPerson.java:220)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.obtainAuthorEmail(GhprbPullRequest.java:266)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:161)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:106)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onPullRequestHook(GhprbRepository.java:233)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction.doIndex(GhprbRootAction.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$2.dispatch(MetaClass.java:164)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:390)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:631)
(...)
```

**Comment by KostyaSha** [comment]
ghprb expects it with catch() but NPE is not good behavior.
NPE is caused because root object is null https://github.com/kohsuke/github-api/blob/d33609ee5711cf42d1884b39597486562e8d037f/src/main/java/org/kohsuke/github/GHPerson.java#L18 
```
GHPullRequest.getHead() return GHCommitPointer, then getUser() returns GHUser that seems is not wrapped with root connection somewhere after passing GHPullRequest to method/constructor.

**Comment by danielr-minted** [comment]
I'm running into this.  Is there a workaround?

**Comment by KostyaSha** [comment]
The reason of this bug is that getMergable() kill internal connection object. This is a test case:
https://gist.github.com/KostyaSha/a46c6892306e767bf26f

**Comment by vbauer** [comment]
I have the same problem..

**Comment by KostyaSha** [comment]
@kohsuke sorry had no time to fix myself because of other bugs in git plugin :(

**Comment by arnoid13** [comment]
I have encountered this on maven artefact 1.66 . Will this make into any new artefacts?

**Comment by KostyaSha** [comment]
Please provide log.
2015-04-06 16:50 GMT+03:00 arnoid13 <notifications@github.com>:

**Comment by arnoid13** [comment]
I've added log into previous comment. I can give you the full sequence of steps-to-reproduce later.
