### ISSUE TITLE
How to search all repos based on a keyword?

### ISSUE THREAD

**Issue by KPRATIK** [kohsuke/github-api#211]
I am trying to do something like this: 
https://api.github.com/search/repositories?q=tetris

This is the code I have now:
GitHub github = GitHub.connectToEnterprise("https://github.corp.<abc>.com/api/v3", "<username>", "<pwd>");
GHRepositorySearchBuilder search = github.searchRepositories();
GHRepositorySearchBuilder s = search.q("audit");
			
PagedSearchIterable<GHRepository> res = s.list();
			
for (GHRepository ghRepository : res) {
  System.out.println(ghRepository.getFullName());;
}

And I get this error:
Exception in thread "main" java.lang.Error: java.net.ConnectException: Operation timed out
	at org.kohsuke.github.Requester$1.fetch(Requester.java:396)
	at org.kohsuke.github.Requester$1.hasNext(Requester.java:363)
	at org.kohsuke.github.PagedSearchIterable$1.hasNext(PagedSearchIterable.java:46)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
	at com.inmobi.pratik.AppTest.main(AppTest.java:71)

Thanks,
Pratik

**Comment by KPRATIK** [comment]
Looks like some network issue as this is working now.. Thanks
