### ISSUE TITLE
RateLimitHandler Bug

### ISSUE THREAD

**Issue by anschwar** [kohsuke/github-api#220]
Hi,

the RateLimitHandler does not to work as intended. 
If using the WAIT implementation the API will still throw an exception and terminate.

The reason therefore is that there is no return statement after the handler execute its onError method.
The problem is allocated in the handleApiError method of the Requester.

https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/Requester.java

**Comment by KostyaSha** [comment]
Any prove? Any logs? Any test case?

**Comment by KostyaSha** [comment]
Do you use Enterprise github? Could you provide PR with fix?

**Comment by anschwar** [comment]
First of all the old code looked like this (1.60)

    /*package*/ void handleApiError(IOException e, HttpURLConnection uc) throws IOException {
        if ("0".equals(uc.getHeaderField("X-RateLimit-Remaining"))) {
            // API limit reached. wait 10 secs and return normally
            try {
                Thread.sleep(10000);
                return;
            } catch (InterruptedException _) {
                throw (InterruptedIOException)new InterruptedIOException().initCause(e);
            }
        }
...

This is nearly the implementation of the current WAIT. It waits 10 seconds and then returns without an exception. The current branch handles the error and then still throws an IO exception

Second. I am fairly new to github and i don't have enterprice github. Is it still possible to provide an PR?

**Comment by KostyaSha** [comment]
Please provide exception reason, not all exceptions should be waited.

**Comment by anschwar** [comment]
Exception in thread "main" java.lang.Error: java.io.IOException: {"message":"API rate limit exceeded for anschwar.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
	at org.kohsuke.github.Requester$1.fetch(Requester.java:410)
	at org.kohsuke.github.Requester$1.hasNext(Requester.java:375)
	at org.kohsuke.github.PagedSearchIterable$1.hasNext(PagedSearchIterable.java:49)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
	at de.hska.github.step.SearchProcessingStep.process(SearchProcessingStep.java:45)
	at de.hska.github.GitHubAnalyzer.process(GitHubAnalyzer.java:21)
	at de.hska.github.GitHubAnalyzer.main(GitHubAnalyzer.java:27)
Caused by: java.io.IOException: {"message":"API rate limit exceeded for anschwar.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:516)
	at org.kohsuke.github.Requester$1.fetch(Requester.java:405)
	... 7 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/search/repositories?q=language%3AScala&page=31
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:471)
	at org.kohsuke.github.Requester.access$300(Requester.java:64)
	at org.kohsuke.github.Requester$1.fetch(Requester.java:399)
	... 7 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/search/repositories?q=language%3AScala&page=31
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:468)
	... 9 more

**Comment by KostyaSha** [comment]
on email i see full stacktrace
``` Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/search/repositories?q=language%3AScala&page=31
 ```

**Comment by anschwar** [comment]
Yes I posted the full one but then i mentioned that you only requested the reason so I edited my comment. However this seems for me to be a consequence of the rate limit.

If you think the behavior of the API is correct, I am ok with it

**Comment by KostyaSha** [comment]
The logic was the next, if you pass wrong user and it not authorised (403) it should throw exception either you will be unable to stop this connection and change user.

**Comment by anschwar** [comment]
I am able to retrieve results (so my credentials are ok) until a certain point.

I have debugged the code and saw that the handler waits certain time until it should return to work again. But this never happens because the code checks the result which has been received before waiting and then throws the exception which imo seems to be wrong.

**Comment by anschwar** [comment]
I found this in the official github api documentation:

Once you go over the rate limit you will receive an error response:

HTTP/1.1 403 Forbidden
Date: Tue, 20 Aug 2013 14:50:41 GMT
Status: 403 Forbidden
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1377013266

{
    "message": "API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}

The 403 is returned if the rate limit is reached

**Comment by kohsuke** [comment]
Fixed in 1.72.
