### ISSUE TITLE
java.lang.IllegalArgumentException: byteString == null

### ISSUE THREAD

**Issue by ligi** [kohsuke/github-api#265]
I hope this is the right repo for this bug:
 
```
￼Branch Indexing Log

Started by timer
FATAL: Failed to recompute children of PassAndroid
java.lang.IllegalArgumentException: byteString == null
    at okio.Buffer.write(Buffer.java:787)
    at com.squareup.okhttp.Cache$Entry.readCertificateList(Cache.java:628)
    at com.squareup.okhttp.Cache$Entry.<init>(Cache.java:555)
    at com.squareup.okhttp.Cache.get(Cache.java:194)
    at com.squareup.okhttp.Cache$1.get(Cache.java:139)
    at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:226)
    at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:438)
    at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:389)
    at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:502)
    at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
    at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
    at org.kohsuke.github.Requester.parse(Requester.java:479)
    at org.kohsuke.github.Requester._to(Requester.java:236)
    at org.kohsuke.github.Requester.to(Requester.java:203)
    at org.kohsuke.github.GitHub.isCredentialValid(GitHub.java:447)
    at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:224)
    at jenkins.scm.api.SCMSource.fetch(SCMSource.java:146)
    at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:296)
    at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:151)
    at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:122)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Finished: FAILURE
```

**Comment by oleg-nenashev** [comment]
For me it seems to be a network connection issue, which does not allow to retrieve the data.
BTW seems it causes a bug in okhttp

**Comment by oleg-nenashev** [comment]
It has been also reported here: https://github.com/square/okhttp/issues/2281

**Comment by ligi** [comment]
Thanks for looking into it - network is completely fine

**Comment by ligi** [comment]
If anyone has the same problem: rm -rf org.jenkinsci.plugins.github.GitHubPlugin.cache/

**Comment by KostyaSha** [comment]
Probably branch source plugin polluted cache (i commented it in their PR, but they ignored it), i don't recommend using branch source plugin until they remove their custom connector.

**Comment by oleg-nenashev** [comment]
CC @jglick @amuniz @recena

**Comment by ligi** [comment]
Just had the same error again - then I thought about disabling the branch source plugin - but I cannot deactivate it ( only revert from 1.4 to 1.3 ) - the checkbox for deactivation is disabled. Also I have the feeling then I would miss the feature that made Jenkins2 so interesting for me ;-)

**Comment by KostyaSha** [comment]
In this case jenkins2 is  marketing, there is nothing specific for this plugin to rely on 2.x.
@ligi because this plugin is still not stable you can fork it and exclude their custom connector. If this would work, then you found the root of issue.

**Comment by ligi** [comment]
> In this case jenkins2 is marketing, there is nothing specific for this plugin to rely on 2.x.

ah I was under the impression that this plugin is behind this new feature that jenkins can monitor my github project for new and deleted branches to create folders/jobs for this - because this was what made it interesting for me

**Comment by KostyaSha** [comment]
@ligi yes, it can. It just the job of new type that scans GH org and creates jobs.

**Comment by amuniz** [comment]
@ligi 

> ah I was under the impression that this plugin is behind this new feature that jenkins can monitor my github project

Yes, it is (`github-branch-source`).

@KostyaSha 

> there is nothing specific for this plugin to rely on 2.x.

It does not rely on 2.0. Only `1.609.3` is required.

> Probably branch source plugin polluted cache

Could you be more specific please? I don't see how plain HTTP calls can pollute a cache.

**Comment by KostyaSha** [comment]
@amuniz https://github.com/jenkinsci/github-branch-source-plugin/pull/30#issuecomment-193824820
As usual it was ignored. And in the same way @kohsuke did what he personally wants here https://github.com/jenkinsci/github-api-plugin/commit/185541aded1daeb3e549595d0008629a950470dd#commitcomment-16569441
About the second incident probably i should wrote to jenkins-board.

**Comment by ligi** [comment]
still experiencing this problem with stock jenkins 2.2 - have to delete the cache all 2-3 days - if there is anything I can do to help circle the problem better?

**Comment by kohsuke** [comment]
Some of the comment went off sideways and distracts from the fundamental issue here, but the problem seems to be that OkHttp can cause cache corruption and if/when it happens it cannot recover from that without a human intervention.

Given that okhttp treats this is "not reproducible, closed", I think the next step is to file a ticket to okhttp asking them to gracefully recover from cache corruption like this.

I'm afraid there's nothing github-api can do with this problem.

**Comment by irvingoe** [comment]
Is this issue resolved? I am facing the same issue when trying to enable the "GitHub Pull Requests" checkbox in the Pipeline Configuration.

```
Stack trace

javax.servlet.ServletException: java.lang.IllegalStateException: Can't find repo provider for PoC_BO_Demo
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:233)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:225)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Can't find repo provider for PoC_BO_Demo
	at com.google.common.base.Preconditions.checkState(Preconditions.java:172)
	at com.github.kostyasha.github.integration.generic.GitHubTrigger.getRepoProvider(GitHubTrigger.java:159)
	at org.jenkinsci.plugins.github.pullrequest.GitHubPRTrigger.start(GitHubPRTrigger.java:158)
	at org.jenkinsci.plugins.github.pullrequest.GitHubPRTrigger.start(GitHubPRTrigger.java:86)
	at org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty.startTriggers(PipelineTriggersJobProperty.java:103)
	at org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty.reconfigure(PipelineTriggersJobProperty.java:159)
	at org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty.reconfigure(PipelineTriggersJobProperty.java:55)
	at hudson.util.DescribableList.rebuild(DescribableList.java:175)
	at hudson.model.Job.doConfigSubmit(Job.java:1236)
	at sun.reflect.GeneratedMethodAccessor796.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:324)
	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:52)
	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:167)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:100)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	... 64 more
```
