### ISSUE TITLE
Numeric value out of range of int

### ISSUE THREAD

**Issue by ievgen-kolomiiets** [kohsuke/github-api#387]
I use GitHub commit status plugin to set commit status at the end of the build and get next error:
```
com.fasterxml.jackson.core.JsonParseException: Numeric value (4295001555) out of range of int
 at [Source: {"url":"https://api.github.com/repos/organiztion/repo/statuses/120ba5d2a8719c59a8c5b28b116049330121349e","id":4295001555,"state":"success","description":"Build #4 succeeded in 1 min 8 sec","target_url":"target_url","context":"context","created_at":"2017-10-18T14:36:05Z","updated_at":"2017-10-18T14:36:05Z"}; line: 1, column: 134]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:928)
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:866)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:694)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:306)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:286)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
Caused: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4295001555) out of range of int
 at [Source: {"url":"https://api.github.com/repos/organization/repo/statuses/120ba5d2a8719c59a8c5b28b116049330121349e","id":4295001555,"state":"success","description":"Build #4 succeeded in 1 min 8 sec","target_url":"target_url","context":"context"}; line: 1, column: 134]
 at [Source: {"url":"https://api.github.com/repos/organization/repo/statuses/120ba5d2a8719c59a8c5b28b116049330121349e","id":4295001555,"state":"success","description":"Build #4 succeeded in 1 min 8 sec","target_url":"target_url","context":"context","created_at":"2017-10-18T14:36:05Z","updated_at":"2017-10-18T14:36:05Z"}; line: 1, column: 124] (through reference chain: org.kohsuke.github.GHCommitStatus["id"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1607)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:278)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at org.kohsuke.github.Requester.parse(Requester.java:616)
Caused: java.io.IOException: Failed to deserialize {"url":"https://api.github.com/repos/organization/repo/statuses/120ba5d2a8719c59a8c5b28b116049330121349e","id":4295001555,"state":"success","description":"Build #4 succeeded in 1 min 8 sec","target_url":"target_url","context":"context","created_at":"2017-10-18T14:36:05Z","updated_at":"2017-10-18T14:36:05Z"}
	at org.kohsuke.github.Requester.parse(Requester.java:618)
Caused: org.kohsuke.github.HttpException: Server returned HTTP response code: 201, message: 'Created' for URL: https://api.github.com/repos/organization/repo/statuses/120ba5d2a8719c59a8c5b28b116049330121349e
	at org.kohsuke.github.Requester.parse(Requester.java:633)
	at org.kohsuke.github.Requester.parse(Requester.java:594)
	at org.kohsuke.github.Requester._to(Requester.java:272)
	at org.kohsuke.github.Requester.to(Requester.java:234)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1071)
	at org.jenkinsci.plugins.github.status.GitHubCommitStatusSetter.perform(GitHubCommitStatusSetter.java:160)
Caused: org.jenkinsci.plugins.github.common.CombineErrorHandler$ErrorHandlingException
	at org.jenkinsci.plugins.github.common.CombineErrorHandler.handle(CombineErrorHandler.java:74)
	at org.jenkinsci.plugins.github.status.GitHubCommitStatusSetter.perform(GitHubCommitStatusSetter.java:164)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:682)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
	at hudson.model.Run.execute(Run.java:1762)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
```

It looks like response from GitHub API contains `id` value `4295001555` that is bigger than `int`.

**Comment by OleksandrBerezianskyi** [comment]
same here

**Comment by joppa27** [comment]
looks like the golang github-api client has similar issues as well:
https://github.com/google/go-github/issues/597

also found this post from a support issue, where it was suggested to use int64(Long) for the `id` field
https://platform.github.community/t/a-few-issues-ive-had-with-the-projects-preview-api/531/3
> When we refer to something as an "int", it's a 32-bit int. That being said, I'd like to stress that it may change in the future, and we'd do our best to communicate that to you should that day come. Based on that information, we'd recommend using an unsigned 64-bit integer.

**Comment by akeithball** [comment]
Same here.  Started experiencing this issue on Wednesday, Oct. 18, 2017.

**Comment by rdsubhas** [comment]
sorry for the +1, same here

**Comment by aburmeis** [comment]
provided a potential fix in PR #388 but would need at least to run the tests

**Comment by egormasalitin** [comment]
Same here

**Comment by moleksyuk** [comment]
Hi @kohsuke 
Any plans to merge https://github.com/kohsuke/github-api/pull/388 ?

Thanks.

**Comment by Eric-Fontana-Bose** [comment]
same here.

**Comment by kisoku** [comment]
Has anyone managed to get #388 to build ? I have been unable to do so both with oracle java 8 or openjdk 8.

**Comment by avielb** [comment]
Same here. 
got it on:
jenkins 2.85

**Comment by jglick** [comment]
Please track in [JENKINS-47601](https://issues.jenkins-ci.org/browse/JENKINS-47601).

**Comment by shevek** [comment]
+1

**Comment by Harriebo** [comment]
+1
