### ISSUE TITLE
NPE in GHPerson.populate

### ISSUE THREAD

**Issue by liborbitala** [kohsuke/github-api#395]
Hi, 

after updating to version 1.90 of GitHub API in our Jenkins, we have a problem when getting info about author of PullRequest for some users. It is blocking our automation of Jenkins builds using Github Pull Request Builder plugin. Interesting thing is that the issue is happening only for some users' Pull Requests. For others everything works fine. We haven't found any suspicious pattern in users' settings.

The error looks as follows:

Unable to handle comment for PR# 266904472, repo: xxx/xxx-xxx
java.lang.NullPointerException
    at org.kohsuke.github.GHPerson.populate(GHPerson.java:44)
    at org.kohsuke.github.GHPerson.getEmail(GHPerson.java:231)
    at org.jenkinsci.plugins.ghprb.GhprbPullRequest.getAuthorEmail(GhprbPullRequest.java:726)
    at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:54)
    at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:417)
    at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:410)
    at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:244)
    at org.jenkinsci.plugins.ghprb.GhprbRepository.onIssueCommentHook(GhprbRepository.java:342)
    at org.jenkinsci.plugins.ghprb.GhprbTrigger.handleComment(GhprbTrigger.java:637)
    at org.jenkinsci.plugins.ghprb.GhprbRootAction$1.run(GhprbRootAction.java:233)

According to report in Jenkins Jira (https://issues.jenkins-ci.org/browse/JENKINS-47848) it seems that downgrade to 1.86 should help, but we need to use 1.90 because of other issues.

Could you look onto it or provide some workaround?

Thank you.

**Comment by Rechi** [comment]
maybe #396 fixes your (and my) issue

**Comment by Rechi** [comment]
@liborbitala try [github-api-1.90-NPE.zip](https://github.com/kohsuke/github-api/files/1461672/github-api-1.90-NPE.zip) this is 1.90 including my NPE fix.
For me it looks like it solved the issue.

**Comment by kohsuke** [comment]
Looks like #396 is merged.
