### ISSUE TITLE
NullPointerException in org.kohsuke.github.GHContent.read

### ISSUE THREAD

**Issue by turbanoff** [kohsuke/github-api#414]
Hello.
I'm trying to use github search API and sometimes got NPE. (tailApiUrl is null)

    Exception in thread "main" java.lang.NullPointerException
	at org.kohsuke.github.GitHub.getApiURL(GitHub.java:297)
	at org.kohsuke.github.Requester.asStream(Requester.java:327)
	at org.kohsuke.github.GHContent.read(GHContent.java:117)

Used version: `org.kohsuke:github-api:1.92`

![default](https://user-images.githubusercontent.com/741251/36343870-e114b9e4-1422-11e8-830a-907720878d38.png)

**Comment by kohsuke** [comment]
I wonder if '#' in the file name is tripping up something.

The repository seems to be gone, but can you create a test case for me?

(Marking as closed until the additional information arrives, please reopen when you have more data)
