### ISSUE TITLE
https://api.github.com/user  response code -1

### ISSUE THREAD

**Issue by attti** [kohsuke/github-api#418]
got error when our pull request builder plugin trying to connect to github.
Feb 23, 2018 4:08:00 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbGitHubAuth buildConnection
Unable to connect using credentials: ________________________________
org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/user
	at org.kohsuke.github.Requester.parse(Requester.java:633)
	at org.kohsuke.github.Requester.parse(Requester.java:594)
	at org.kohsuke.github.Requester._to(Requester.java:272)
	at org.kohsuke.github.Requester.to(Requester.java:234)
	at org.kohsuke.github.GitHub.getMyself(GitHub.java:384)
	at org.kohsuke.github.GitHub.<init>(GitHub.java:158)
	at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:207)
	at org.jenkinsci.plugins.ghprb.GhprbGitHubAuth.buildConnection(GhprbGitHubAuth.java:195)
	at org.jenkinsci.plugins.ghprb.GhprbGitHubAuth.getConnection(GhprbGitHubAuth.java:204)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.getGitHub(GhprbTrigger.java:431)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:86)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:130)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:300)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:272)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:602)
	... 22 more

**Comment by 0505gonzalez** [comment]
Having the same issue.

@kohsuke What version of TLS is this plugin using? It looks like github will not accept requests with TLS versions less than 1.2

**Comment by 0505gonzalez** [comment]
https://github.com/blog/2507-weak-cryptographic-standards-removed

**Comment by 0505gonzalez** [comment]
@attti I solved this issue by upgrading to Java 8. Additionally, you can force java 7 to use TLS 1.2 by using this java option: `-Dhttps.protocols=TLSv1.2`

**Comment by attti** [comment]
@0505gonzalez 
Thanks, upgrading jdk 1.8 solved issue. will close this ticket.
