### ISSUE TITLE
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.deser.SettableBeanProperty.<init>

### ISSUE THREAD

**Issue by Karpinchyk** [kohsuke/github-api#419]
I am very sorry if this issue has been already addressed somewhere. I tried to google but didn't find any references.

Starting at version 1.90 of github-api a dropwizard app gives an exception when started. Previous versions of the lib (1 - 1.89) work fine.

Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.deser.SettableBeanProperty.<init>(Lcom/fasterxml/jackson/databind/deser/SettableBeanProperty;Lcom/fasterxml/jackson/databind/JsonDeserializer;)V
	at com.fasterxml.jackson.module.afterburner.deser.OptimizedSettableBeanProperty.<init>(OptimizedSettableBeanProperty.java:50)
	at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.<init>(SettableObjectMethodProperty.java:21)
	at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.withValueDeserializer(SettableObjectMethodProperty.java:38)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:462)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.resolve(SuperSonicBeanDeserializer.java:79)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4178)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3967)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2264)
	at io.dropwizard.configuration.YamlConfigurationFactory.build(YamlConfigurationFactory.java:123)
	at io.dropwizard.configuration.YamlConfigurationFactory.build(YamlConfigurationFactory.java:87)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:124)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:72)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
...

**Comment by kohsuke** [comment]
You must be using an incompatible version of Jackson somewhere.

**Comment by mickybissi** [comment]
Hi koshuke,

I'm also facing the same issue.


java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.deser.SettableBeanProperty.<init>(Lcom/fasterxml/jackson/databind/deser/SettableBeanProperty;Lcom/fasterxml/jackson/databind/JsonDeserializer;)V

	at com.fasterxml.jackson.module.afterburner.deser.OptimizedSettableBeanProperty.<init>(OptimizedSettableBeanProperty.java:48)
	at com.fasterxml.jackson.module.afterburner.deser.SettableLongFieldProperty.<init>(SettableLongFieldProperty.java:21)
	at com.fasterxml.jackson.module.afterburner.deser.SettableLongFieldProperty.withValueDeserializer(SettableLongFieldProperty.java:35)
	at com.fasterxml.jackson.module.afterburner.deser.SettableLongFieldProperty.withValueDeserializer(SettableLongFieldProperty.java:9)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:475)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.resolve(SuperSonicBeanDeserializer.java:79)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:466)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.resolve(SuperSonicBeanDeserializer.java:79)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4389)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4168)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2467)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:125)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:77)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:114)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:63)
	at io.dropwizard.testing.junit.DropwizardAppRule.startIfRequired(DropwizardAppRule.java:107)
	at io.dropwizard.testing.junit.DropwizardAppRule.access$000(DropwizardAppRule.java:30)
	at io.dropwizard.testing.junit.DropwizardAppRule$1.evaluate(DropwizardAppRule.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


My maven dependencies are as follows:

<dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.10.0</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.10.0</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.10.0</version>
        </dependency

Can you please help me . what is incompatible here?

Thanks a lot in advance

**Comment by bitwiseman** [comment]
Are you sure?  You'll want to look at the output from `mvn dependency:tree -Dverbose` to see where you might be loading incompatible versions.
