### ISSUE TITLE
getEvents fails periodically with odd exception

### ISSUE THREAD

**Issue by mebigfatguy** [kohsuke/github-api#92]
Occasionally a call to getEvents will throw with the following exception. I'm assuming this is just the github rest layer being flaky or somethimg, but just posting it, in case there's something else going on

ERROR 21:37:25 Failed fetching events from github
java.net.UnknownHostException: api.github.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1250) ~[na:1.7.0_55]
	at java.net.InetAddress.getAllByName(InetAddress.java:1162) ~[na:1.7.0_55]
	at java.net.InetAddress.getAllByName(InetAddress.java:1098) ~[na:1.7.0_55]
	at com.squareup.okhttp.internal.Dns$1.getAllByName(Dns.java:29) ~[okhttp-1.5.3.jar:na]
	at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232) ~[okhttp-1.5.3.jar:na]
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124) ~[okhttp-1.5.3.jar:na]
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:233) ~[okhttp-1.5.3.jar:na]
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:180) ~[okhttp-1.5.3.jar:na]
	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:366) ~[okhttp-1.5.3.jar:na]
	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:319) ~[okhttp-1.5.3.jar:na]
	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:187) ~[okhttp-1.5.3.jar:na]
	at com.squareup.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210) ~[okhttp-1.5.3.jar:na]
	at com.squareup.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25) ~[okhttp-1.5.3.jar:na]
	at org.kohsuke.github.Requester.parse(Requester.java:359) ~[github-api-1.53.jar:na]
	at org.kohsuke.github.Requester._to(Requester.java:180) ~[github-api-1.53.jar:na]
	at org.kohsuke.github.Requester.to(Requester.java:155) ~[github-api-1.53.jar:na]

**Comment by kohsuke** [comment]
I agree, doesn't look like there's anything we can do from our side.
